seed: 42
log_interval: 100
num_att_plot: 0
num_workers: 16
sort_in_batch: descending       # how to sort data in making batch
sort_batch: descending          # how to sort created batches
batch_type: length
batch_bins: 1200 # 57,600 # 12 * 4 * 1,200 = 1,800 frames * 32 (n GPU)
max_utt_len: null
accum_grad: 12
max_epoch: 50
patience: none
init: default
best_model_criterion:
-   - valid
    - acc
    - max
keep_nbest_models: 10

dry_run: false
use_amp: false
cudnn_deterministic: true
cudnn_benchmark: true

optim: adamw
optim_conf:
    lr: 0.001
    betas: [0.9, 0.98]
    eps: 0.000000001
    weight_decay: 0.03
scheduler: cosinewarmup
scheduler_conf:
    warmup_epochs: 5
    num_epochs: 50

# ==============
# Train Setup
# ==============

# Log
use_wandb: True


# Data
preprocessor: default
preprocessor_conf:
    fps: 25

# ==============
# Model Setup
# ``Frontend -> Augmentation -> Normalization 
#   -> PreEncoder -> Encoder -> PostEncoder -> Decoder``
# ==============

# Model Configuration
model: iipnet
model_conf:
    ctc_weight: 0.1
    lsm_weight: 0.1
    length_normalized_loss: false
    extract_feats_in_collect_stats: false
    extract_order: ["aug", "norm", "front"]
sync_batchnorm: true

# FrontEnds
frontend: resnet
frontend_conf:
    in_channels: 1 # grays
    out_channels: 512
    kernel_size: [5, 7, 7]
    stride: [1, 2, 2]
    padding: [2, 3, 3]
    relu_type: swish
    pretrained_pt: ../../lrw/pretrained/lrw_resnet18_dctcn_video_frontend.pth
    freeze_weights: false
    
# Augmentation
aug: null
aug_conf: null
# aug: corrupt
# aug_conf: 
#     mode: 'occlusion_and_noise'
#     noise_args:
#         # Segment
#         max_N: 3
#         min_N: 1
#         max_ratio: 0.5
#         min_ratio: 0.3
#         prob: 0.3
#         # Noise
#         gaussian_kernel_size: 7
#         gaussian_sigma_min: 0.1
#         gaussian_sigma_max: 2.0
#         noise_var_max: 0.2
#         noise_blur_ratio: 0.5
#     occlusion_args:
#         # Segment
#         max_N: 3
#         min_N: 1
#         max_ratio: 0.5
#         min_ratio: 0.3
#         prob: 0.8 
#         # Noise
#         occlusion_dir: ./data/coco_object/object_image_sr
#         occlusion_mask_dir: ./data/coco_object/object_mask_x4
#         color: gray
#     crop_args: null
#     flip_args: 
#         flip_prob: 0.5

# Normalization
normalize: global_mvn
normalize_conf:
    norm_means: true
    norm_vars: true

# Pre-encoding
preencoder: null
preencoder_conf: null

encoder: conformer
encoder_conf:
    output_size: 256
    attention_heads: 8
    linear_units: 2048
    num_blocks: 12
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    attention_dropout_rate: 0.1
    input_layer: linear_
    normalize_before: true
    macaron_style: true
    rel_pos_type: latest
    pos_enc_layer_type: rel_pos
    selfattention_layer_type: rel_selfattn
    activation_type: swish
    ff_activation_type: relu
    use_cnn_module: true
    cnn_module_kernel: 31

# Post-encoding
postencoder: null

# Decoding
decoder: transformer
decoder_conf:
    attention_heads: 8
    linear_units: 2048
    num_blocks: 6
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    self_attention_dropout_rate: 0.1
    src_attention_dropout_rate: 0.1