seed: 2023
log_interval: 400
num_att_plot: 0
num_workers: 4
sort_in_batch: descending       # how to sort data in making batch
sort_batch: descending          # how to sort created batches
batch_type: numel
batch_bins: 16000000
accum_grad: 4
max_epoch: 200
patience: none
init: none
best_model_criterion:
-   - valid
    - acc
    - max
keep_nbest_models: 10

use_amp: true
cudnn_deterministic: false
cudnn_benchmark: false

optim: adam
optim_conf:
    lr: 0.0004
    weight_decay: 0.000001
scheduler: warmuplr
scheduler_conf:
    warmup_steps: 25000


# ==============
# Train Setup
# ==============

# Log
use_wandb: false

# Noise dynamics
noise_scp: dump/raw/noise.scp
noise_apply_prob: 1.0
noise_db_range: '-5_20'

# Data
preprocessor: default

# ==============
# Model Setup
# ``Frontend -> Augmentation -> Normalization 
#   -> PreEncoder -> Encoder -> PostEncoder -> Decoder``
# ==============

# Model Configuration
model: espnet
model_conf:
    ctc_weight: 0.3
    lsm_weight: 0.1
    length_normalized_loss: false
    extract_feats_in_collect_stats: true

# FrontEnds
audio_frontend: null
visual_frontend: null
    
# Augmentation
audio_specaug: null
audio_specaug_conf: null
visual_aug: null
visual_aug_conf: null

# Normalization
audio_normalize: global_mvn
visual_normalize: global_mvn

# Pre-encoding
audio_preencoder: res18
audio_preencoder_conf:
    in_channels: 1
    out_channels: 512
    kernel_size: 80 
    stride: 4
    padding: 40
    dropout: 0.1

visual_preencoder: res18
visual_preencoder_conf:
    in_channels: 1 # gray
    out_channels: 512
    kernel_size: [5, 7, 7]
    stride: [1, 2, 2]
    padding: [2, 3, 3]
    dropout: 0.1

# Encoding
encoder: late
fusion: mlp
fusion_conf:
    audio_input_size: 256
    visual_input_size: 256
    output_size: 256
    expand_ratio: 2
    dropout_rate: 0.1
align: interpolate

audio_encoder: conformer
audio_encoder_conf:
    input_size: 512
    output_size: 256
    attention_heads: 4
    linear_units: 1024
    num_blocks: 12
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    attention_dropout_rate: 0.1
    input_layer: conv2d
    normalize_before: true
    macaron_style: true
    rel_pos_type: latest
    pos_enc_layer_type: rel_pos
    selfattention_layer_type: rel_selfattn
    activation_type: swish
    use_cnn_module: true
    cnn_module_kernel: 31

visual_encoder: conformer
visual_encoder_conf:
    input_size: 512
    output_size: 256
    attention_heads: 4
    linear_units: 1024
    num_blocks: 12
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    attention_dropout_rate: 0.1
    input_layer: conv2d
    normalize_before: true
    macaron_style: true
    rel_pos_type: latest
    pos_enc_layer_type: rel_pos
    selfattention_layer_type: rel_selfattn
    activation_type: swish
    use_cnn_module: true
    cnn_module_kernel: 31

# Post-encoding
audio_postencoder: null
visual_postencoder: null

# Decoding
decoder: transformer
decoder_conf:
    attention_heads: 4
    linear_units: 2048
    num_blocks: 6
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    self_attention_dropout_rate: 0.1
    src_attention_dropout_rate: 0.1