seed: 42
log_interval: 1000
num_att_plot: 0
num_workers: 8
sort_in_batch: descending       # how to sort data in making batch
sort_batch: descending          # how to sort created batches
batch_type: length
batch_bins: 9216000 # 9216000 # 36,864,000 # 20 * 4 * 460,800 = 1,800 frames / 25 (FPS) * 16,000 (SR) * 32 (n GPU)
# max_utt_len: 16000 # 64,000 / 96,000 / 192,000 / 384,000
accum_grad: 4
max_epoch: 75
patience: none
init: default
best_model_criterion:
-   - valid
    - acc
    - max
keep_nbest_models: 10
nbest_averaging_interval: 30

dry_run: false
use_amp: false
cudnn_deterministic: true
cudnn_benchmark: true

# optim: adamw
# optim_conf:
#     lr: 0.001
#     betas: [0.9, 0.98]
#     eps: 0.00000001
#     weight_decay: 0.03
# scheduler: cosinewarmup
# scheduler_conf:
#     warmup_epochs: 2
#     num_epochs: 20

optim: adamw
optim_conf:
    betas: [0.9, 0.98]
    eps: 0.00000001
    lr: 0.001
    weight_decay: 0.000001
scheduler: cosinewarmup
scheduler_conf:
    warmup_epochs: 5
    num_epochs: 100

# ==============
# Train Setup
# ==============

# Log
use_wandb: False
wandb_project: KoreanAI2023
wandb_name: debug_0.0

# Noise dynamics
# noise_scp: data/noise.scp
# noise_apply_prob: 1.0
# noise_db_range: '-5_0_5_10_15_20_9999'

# Data
preprocessor: default
preprocessor_conf:
    adaptive_time_mask: True
    adaptive_time_mask_rate: 0.4
    adaptive_time_mask_period: 1.0
    fs: 16000
#     speech_speed_perturb: 0.9_1.0_1.1

# ==============
# Model Setup
# ``Frontend -> Augmentation -> Normalization 
#   -> PreEncoder -> Encoder -> PostEncoder -> Decoder``
# ==============

# Model Configuration
model: espnet
model_conf:
    token_normalize: True
    report_cer: True
    report_wer: False
    ctc_weight: 0.1
    lsm_weight: 0.1
    length_normalized_loss: false
    extract_feats_in_collect_stats: false
    extract_order: ["front", "aug", "norm"]
sync_batchnorm: false

# FrontEnds
# frontend: resnet
# frontend_conf:
#     in_channels: 1
#     out_channels: 512
#     kernel_size: 80 
#     stride: 4
#     padding: 38
#     relu_type: swish
#     freeze_weights: false
frontend: default
frontend_conf:
    n_fft: 512
    hop_length: 160
    n_mels: 80
    
# Augmentation
specaug: specaug
specaug_conf:
    apply_time_warp: true
    time_warp_window: 5
    time_warp_mode: bicubic
    apply_freq_mask: true
    freq_mask_width_range:
    - 0
    - 30
    num_freq_mask: 2
    apply_time_mask: true
    time_mask_width_range:
    - 0
    - 40
    num_time_mask: 2

# Normalization
normalize: utterance_mvn
normalize_conf:
    norm_means: true
    norm_vars: true

# Pre-encoding
preencoder:
preencoder_conf:

encoder: conformer
encoder_conf:
    output_size: 256
    attention_heads: 4
    linear_units: 2048
    num_blocks: 12
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    attention_dropout_rate: 0.1
    input_layer: conv2d
    normalize_before: true
    macaron_style: true
    rel_pos_type: latest
    pos_enc_layer_type: rel_pos
    selfattention_layer_type: rel_selfattn
    activation_type: swish
    use_cnn_module: true
    cnn_module_kernel: 31

# Post-encoding
# postencoder: linear
# postencoder_conf:
#     output_size: 640

# Decoding
decoder: transformer
decoder_conf:
    attention_heads: 4
    linear_units: 2048
    num_blocks: 1
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    self_attention_dropout_rate: 0.1
    src_attention_dropout_rate: 0.1
